 DROP TABLE  HR_MEMBER;
 CREATE TABLE "SPRING"."HR_MEMBER" 
   (    "U_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    "NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
    "PASSWD" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
    "U_LEVEL" NUMBER(2,0) , 
    "LOGIN" NUMBER(8,0) , 
    "RECOMMEND" NUMBER(8,0) , 
    "EMAIL" VARCHAR2(320 BYTE), 
    "REG_DT" DATE DEFAULT SYSDATE, 
     CONSTRAINT "PK_HR_MEMBER" PRIMARY KEY ("U_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SPRING_TS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SPRING_TS" ;